### ISSUE TITLE
Run on ubuntu 18

### ISSUE THREAD

**Issue by Marverlises** [xkiwilabs/Multi-Agent-DDPG-using-PTtorch-and-ML-Agents#2]
Excuse me, I have some questions about the Unity Environment on the Linux,
i used to run the project on my cloud service, but the bug shows as below
```
ssh://parsley@119.45.234.179:22/home/parsley/anaconda3/envs/RL_test/bin/python3.6 -u /home/parsley/Python_projects/The_finnal_Tennis/train.py
Found path: /home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis.x86_64
Mono path[0] = '/home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis_Data/Managed'
Mono config path = '/home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis_Data/MonoBleedingEdge/etc'
Preloaded 'libgrpc_csharp_ext.x64.so'
Unable to preload the following plugins:
	ScreenSelector.so
	libgrpc_csharp_ext.x86.so
	ScreenSelector.so
Logging to /home/parsley/.config/unity3d/Unity Technologies/Unity Environment/Player.log
Stacktrace:
......
################at the end shows######################
Traceback (most recent call last):
  File "/home/parsley/Python_projects/The_finnal_Tennis/train.py", line 47, in <module>
    env = UnityEnvironment(file_name=r"/home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis.x86_64")
  File "/home/parsley/anaconda3/envs/RL_test/lib/python3.6/site-packages/unityagents/environment.py", line 64, in __init__
    aca_params = self.send_academy_parameters(rl_init_parameters_in)
  File "/home/parsley/anaconda3/envs/RL_test/lib/python3.6/site-packages/unityagents/environment.py", line 505, in send_academy_parameters
    return self.communicator.initialize(inputs).rl_initialization_output
  File "/home/parsley/anaconda3/envs/RL_test/lib/python3.6/site-packages/unityagents/rpc_communicator.py", line 60, in initialize
    "The Unity environment took too long to respond. Make sure that :\n"
unityagents.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
	 The environment does not need user interaction to launch
	 The Academy and the External Brain(s) are attached to objects in the Scene
	 The environment and the Python interface have compatible versions.

Process finished with exit code 1

```
The environment on Linux path is Tennis.x86_64, right?
I want to get some advice about how to run this on Ubuntu, I'm a noviciate and Thank you  sincerely in advance!

**Comment by doveeee3** [comment]
> Excuse me, I have some questions about the Unity Environment on the Linux, i used to run the project on my cloud service, but the bug shows as below
> 
> ```
> ssh://parsley@119.45.234.179:22/home/parsley/anaconda3/envs/RL_test/bin/python3.6 -u /home/parsley/Python_projects/The_finnal_Tennis/train.py
> Found path: /home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis.x86_64
> Mono path[0] = '/home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis_Data/Managed'
> Mono config path = '/home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis_Data/MonoBleedingEdge/etc'
> Preloaded 'libgrpc_csharp_ext.x64.so'
> Unable to preload the following plugins:
> 	ScreenSelector.so
> 	libgrpc_csharp_ext.x86.so
> 	ScreenSelector.so
> Logging to /home/parsley/.config/unity3d/Unity Technologies/Unity Environment/Player.log
> Stacktrace:
> ......
> ################at the end shows######################
> Traceback (most recent call last):
>   File "/home/parsley/Python_projects/The_finnal_Tennis/train.py", line 47, in <module>
>     env = UnityEnvironment(file_name=r"/home/parsley/Python_projects/The_finnal_Tennis/Tennis_Windows_x86_64/Tennis_Linux/Tennis.x86_64")
>   File "/home/parsley/anaconda3/envs/RL_test/lib/python3.6/site-packages/unityagents/environment.py", line 64, in __init__
>     aca_params = self.send_academy_parameters(rl_init_parameters_in)
>   File "/home/parsley/anaconda3/envs/RL_test/lib/python3.6/site-packages/unityagents/environment.py", line 505, in send_academy_parameters
>     return self.communicator.initialize(inputs).rl_initialization_output
>   File "/home/parsley/anaconda3/envs/RL_test/lib/python3.6/site-packages/unityagents/rpc_communicator.py", line 60, in initialize
>     "The Unity environment took too long to respond. Make sure that :\n"
> unityagents.exception.UnityTimeOutException: The Unity environment took too long to respond. Make sure that :
> 	 The environment does not need user interaction to launch
> 	 The Academy and the External Brain(s) are attached to objects in the Scene
> 	 The environment and the Python interface have compatible versions.
> 
> Process finished with exit code 1
> ```
> 
> The environment on Linux path is Tennis.x86_64, right? I want to get some advice about how to run this on Ubuntu, I'm a noviciate and Thank you sincerely in advance!

hi，Have you solved the problem yet? I have the same problem as you.
